# Copyright 2014 The Ostrich / by Itamar O
# pylint: disable=undefined-variable,invalid-name

"""AddressBook Writer SConscript script"""

Import('*')

module_targets = dict()
module_targets['writer'] = env.Program(
    'writer', ['writer.cc'] + env.get_targets('addressbook'))

Return('module_targets')
