# Copyright 2015 The Ostrich / by Itamar O
# pylint: disable=undefined-variable, invalid-name

"""AddressBook proto-based library SConscript script"""

Import('*')

AbProtos = ['person.proto', 'addressbook.proto']

Proto(AbProtos)
Lib('addressbook', protos=AbProtos)
