# Copyright 2015 The Ostrich / by Itamar O
# pylint: disable=undefined-variable

"""AddressBook Writer SConscript script"""

Import('*')

Prog('reader', 'reader.cc', with_libs='AddressBook::addressbook',
     LIBS=['protobuf'])
